#!/bin/bash
#PBS -M agf18@ifi.unicamp.br
#PBS -N columbus
#PBS -e columbus.err
#PBS -o columbus.out
#PBS -q desenvolvimento
#PBS -l nodes=1:ppn=12

cd $PBS_O_WORKDIR 


. /home/sw/masternode2/intel/20156223/install/composer_xe_2015/bin/compilervars.sh intel64
. /home/sw/masternode2/intel/20156223/install/impi/5.1.2.150/intel64/bin/mpivars.sh


export OMP_NUM_THREADS=$PBS_NP 

export COLUMBUS="/home3/molecula1/maplima/agf18/columbus/Columbus/"


$COLUMBUS/runc -m 20000 > runls  
