#!/bin/bash 

#SBATCH --time=3-00:00:00 
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --partition=nm3
#SBATCH --job-name=adf 

WORKDIR=`pwd`
SCRATCH=/scratch/$USER/$SLURM_JOB_ID
SRUN='srun -N '$SLURM_NNODES' -n '$SLURM_NNODES
export SCM_TMPDIR=/scratch/$USER/adftmp

$SRUN mkdir -p $SCM_TMPDIR
$SRUN mkdir -p $SCRATCH
$SRUN cp $1 $SCRATCH
$SRUN cp gs.t21 fragA1.t21 fragB1.t21  $SCRATCH
#$SRUN cp v* $SCRATCH

cd $SCRATCH
echo "$SRUN hostname"

bash $1 > $1.out
# pyadf $1
 
node=$( sp | grep $SLURM_JOB_ID | awk '{ print $8 }')

module load intel_mkl/18.0.5 python/3.5.2

ssh $node
cp -r $SCRATCH/* $WORKDIR

cd $WORKDIR
$SRUN rm -rf $SCRATCH
