#!/bin/csh

set gms='~/GAMESS/gamess/rungms'
set scr_dir='/tmp'
set loc_dir='/home3/molecula1/maplima/agf18/benzene/gamess-otimizacao/certo'

set JOB='benzene'

cd $scr_dir
rm -f $JOB'.irc'
rm -f $JOB'.dat'
#rm -f $JOB'.F77'

cd $loc_dir
#cp $loc_dir/VNUC.FILE $scr_dir/$JOB'.F77'

$gms $JOB > & $JOB'.log'

mv $scr_dir/$JOB'.dat' $loc_dir/
#mv $scr_dir/$JOB'.OCK' $loc_dir/FOCK.FILE
