#!/bin/bash
#PBS -M agf18@ifi.unicamp.br
#PBS -N psi4
#PBS -e psi4.err
#PBS -o psi4.out
#PBS -q par12 
#PBS -l nodes=1:ppn=12

cd $PBS_O_WORKDIR 

. /home/sw/masternode2/intel/20156223/install/composer_xe_2015/bin/compilervars.sh intel64
. /home/sw/masternode2/intel/20156223/install/impi/5.1.2.150/intel64/bin/mpivars.sh
. $HOME/psi4conda/etc/profile.d/conda.sh
conda activate
export OMP_NUM_THREADS=$PBS_NP 

~/psi4conda/bin/psi4 benzene.inp benzene.log 
